# Install pre-commit hooks via:
# pre-commit install

repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v1.2.3
   hooks:
   - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    name: yapf
    args: ["-i"]

- repo: https://github.com/PyCQA/prospector
  rev: 1.1.7
  hooks:
  - id: prospector
    language: system
    types: [python]
    exclude: "(^docs)|(^.github)"